export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
    'IMSI': 'IMSI',
    'hello world': 'hello world',
    'Provider': 'Provider',
    'Period': 'Period',
    'Previous Month': 'Previous Month',
    'Current Month': 'Current Month',
    'Date': 'Date',
    'Search': 'Search',
    'Pick date': 'Pick date',
    'Results': 'Results',
    'Uplink Bytes': 'Uplink Bytes',
    'Downlink Bytes': 'Downlink Bytes',
    'Total Bytes': 'Total Bytes',
    'Split by': 'Split by',
    'Daily': 'Daily',
    'First Name': 'First Name',
    'Last Name': 'Last Name',
    'Organization': 'Organization',
    'Email Address': 'Email Address',
    'VIN (Last 7)': 'VIN (Last 7)',
    'Phone Number': 'Phone Number',
    'Account Id': 'Account Id',
    'Account Name': 'Account Name',
    'Account Number': 'Account Number',
    'Address Line 1': 'Address Line 1',
    'Address Line 2': 'Address Line 2',
    'City': 'City',
    'State': 'State / Province',
    'Zipcode': 'Zipcode',
    'Country': 'Country',
    'VIN': 'VIN',
    'Make': 'Make',
    'Model': 'Model',
    'Year': 'Year',
    'Device #': 'Device #',
    'Device Type': 'Device Type',
    'IMEI': 'IMEI',
    'CCID': 'CCID',
    'empty_table_msg': 'No records found',
    'account_type': 'Account Type',
    'company_name': 'Company Name',
    'account_category': 'Account Category',
    'account_status': 'Account Status',
    'account_update': 'Account Update',
    'address_mgmt': 'Address Management',
    'billing_info': 'Billing Info',
    'contact_mgmt': 'Contact Management',
    'vehicle_mgmt': 'Update RSA Events',
    'vehicle_swap': 'Update YMMC',
    'reset_pin': 'Reset Pin',
    'device_update': 'Device Update',
    'privacy_pref': 'Privacy Preference',
    'new_device_assoc': 'New Device Association',
    'update_existing_add': 'Update Existing Address',
    'new_address': 'New Address',
    'update': 'Update',
    'key_alerts': 'Key Alerts',
    'key_msg': 'Key Message',
    'update_existing_card': 'Update Existing Card',
    'create_new_card': 'Create New Card',
    'update_existing_contact': 'Update Existing Contact',
    'create_new_contact': 'Create New Contact',
    'update_events': 'Update Events',
    'events': 'Events',
    'address_type': 'Address Type',
    'card_type': 'Card Type',
    'card_holder_name':'Card Holder Name',
    'credit_card_no': 'Credit Card Number',
    'work_phone_no': 'Work Phone #',
    'home_phone_no': 'Home Phone #',
    'mobile_phone_no': 'Mobile Phone #',
    'preferred_contact_mtd': 'Preferred Method of Contact',
    'alt_contact_mtd': 'Alternate Method of Contact',
    'contact_type': 'Contact Type',
    'CVC': 'CVC',
    'expiration_date': 'Expiration Date',
    'validate': 'Validate',
    'vehicle': 'Vehicle',
    'device': 'Device',
    'head_unit_type': 'Head Unit Type',
    'wireless_carrier': 'Wireless Carrier',
    'MDN/MSISDN': 'MDN/MSISDN',
    'chk_vehicle_eligibility': 'Check Vehicle Eligibility',
    'create': 'Create',
    'modify': 'Modify',
    'used': 'Used',
    'remaining': 'Remaining',
    'card_detail': 'Card Details',
     'color': 'Color',
     'device_id': 'Device Id',
     'head_unit': 'Head Unit',
     'Serial#': 'Serial#',
    'created': 'Created',
    'telematic_req_history': 'Telematics Request History',
    'device_event_history': 'Device Event History',
    'subscription_history': 'Subscription History',
    'notifications_history': 'Notifications History',
    'account_mgmt_history': 'Account Management History',
     'from': 'From',
      'to': 'To'
};
