export const LANG_ES_NAME = 'es';

export const LANG_ES_TRANS = {
    'hello world': 'hola mundo',
    'IMSI': 'IMSI',
    'Provider': 'Proveedor',
    'Period': 'Período',
    'Previous Month': 'Mes anterior',
    'Current Month': 'Mes actual',
    'Date': 'Fecha',
    'Search': 'Buscar',
    'Pick date': 'Elegir fecha',
    'Results': 'Resultados',
    'Uplink Bytes': 'Bytes de enlace ascendente',
    'Downlink Bytes': 'Bytes de enlace descendente',
    'Total Bytes': 'Total de bytes',
    'Split by': 'Dividido por',
    'Daily': 'Diariamente',
    'First Name': 'Nombre de pila',
    'Last Name': 'Apellido',
    'Organization': 'Organización',
    'Email Address': 'correo electrónico',
    'VIN (Last 7)': 'VIN (Último 7)',
    'Phone Number': 'Número de teléfono',
    'Account Id': 'ID de la cuenta',
    'Account Name': 'Nombre de la cuenta',
    'Account Number': 'Número de cuenta',
    'Address Line 1': 'Dirección 1',
    'Address Line 2': 'Dirección 2',
    'City': 'Ciudad',
    'State': 'Estado',
    'Zipcode': 'Código postal',
    'Country': 'País',
    'VIN': 'VIN',
    'Make': 'Hacer',
    'Model': 'Modelo',
    'Year': 'Año',
    'Device #': 'Dispositivo #',
    'Device Type': 'Tipo de dispositivo',
    'IMEI': 'IMEI',
    'CCID': 'CCID',
    'empty_table_msg': 'No se encontraron reocrds',
    // yet to translate
    'account_type': 'Tipo de cuenta',
    'company_name': 'nombre de empresa',
    'account_category': 'Categoría de cuenta',
    'account_status': 'estado de la cuenta',
    'account_update': 'Actualización de cuenta',
    'address_mgmt': 'Gestión de Direcciones',
    'billing_info': 'Información de facturación',
    'contact_mgmt': 'Gestión de contactos',
    'vehicle_mgmt': 'Gestión de Vehículos',
    'vehicle_swap': 'Intercambio de vehículos',
    'reset_pin': 'Pin de reinicio',
    'device_update': 'Actualización del dispositivo',
    'privacy_pref': 'Preferencia de privacidad',
    'new_device_assoc': 'Nueva Asociación de Dispositivos',
    'update_existing_add': 'Actualizar la dirección existente',
    'new_address': 'Nueva direccion',
    'update': 'Actualizar',
    'key_alerts': 'Alertas claves',
    'key_msg': 'Mensaje clave',
    'validate': 'Validar',
    'vehicle': 'vehículo',
    'device': 'dispositivo',
    'head_unit_type': 'Tipo de unidad principal',
    'wireless_carrier': 'Proveedor de servicios inalámbricos',
    'MDN/MSISDN': 'MDN/MSISDN',
    'chk_vehicle_eligibility': 'Comprobar la elegibilidad del vehículo',
    'create': 'Crear',
    'modify': 'Modificar',
    'card_detail': 'Detalles de tarjeta',
    'update_existing_card': 'Actualizar tarjeta existente',
    'create_new_card': 'Crear una nueva tarjeta',
    'update_existing_contact': 'Actualizar contacto existente',
    'create_new_contact': 'Crear nuevo contacto',
    'update_events': 'Actualizar eventos',
    'events': 'Eventos',
    'card_type': 'Tipo de tarjeta',
    'card_holder_name':'Nombre del titular de la tarjeta',
    'credit_card_no': 'Número de tarjeta de crédito',
    'work_phone_no': 'Teléfono del trabajo#',
    'home_phone_no': 'Teléfono de casa#',
    'mobile_phone_no': 'Teléfono móvil#',
    'preferred_contact_mtd': 'Método de contacto preferido',
    'alt_contact_mtd': 'Método Alterno de Contacto',
    'contact_type': 'Tipo de Contacto',
    'CVC': 'CVC',
    'expiration_date': 'Fecha de caducidad',
    'address_type': 'Address Type spn',    
    'used': 'Used',
    'remaining': 'Remaining',
    'color': 'Color',
    'device_id': 'Device Id',
    'head_unit': 'Head Unit',
    'Serial#': 'Serial#',
    'created': 'Creado',
    'telematic_req_history': 'Telemática',
    'device_event_history': 'Historial de eventos del dispositivo',
    'subscription_history': 'Historial de Suscripciones',
    'notifications_history': 'Historial de notificaciones',
    'account_mgmt_history': 'Historial de gestión de cuentas',
     'from': 'De',
      'to': 'A'
    
};
